apiVersion: v1
kind: Service
metadata:
  name: {{ include ".helm.fullname" . }}
  labels:
    app: {{ include ".helm.name" . }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 3000
    protocol: TCP
  selector:
    app: {{ include ".helm.name" . }}





