name: CI/CD Pipeline

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nodejs_server:latest

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Wait for Docker image to be available
        id: wait_for_image
        run: |
          timeout=300
          while [ $timeout -gt 0 ]; do
            docker pull ${{ secrets.DOCKER_USERNAME }}/nodejs_server:latest && exit 0
            sleep 10
            timeout=$((timeout - 10))
          done
          echo "Timed out waiting for Docker image"
          exit 1

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update docker-compose and deploy
        run: |
          cd ~/Simple-NodeJS-Server
          sed -i 's|image: .*/nodejs_server:.*|image: '"${{ secrets.DOCKER_USERNAME }}/nodejs_server:latest"'|' docker-compose.yml
          docker-compose pull
          docker-compose up -d

