name: CI/CD Pipeline

on:
  push:
    tags:
      - 'v*'  # Реагировать на пуш тегов, начинающихся с 'v'

jobs:
  build_and_deploy:
    runs-on: self-hosted

    env:
      NODEJS_SERVER_TAG: ${{ github.ref }}  # Используем тег GitHub референса (например, v1.0.18)

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nodejs_server:${NODEJS_SERVER_TAG}  # Используем переменную окружения для задания тега

      - name: Update docker-compose and deploy
        run: |
          sed -i "s|image: .*/nodejs_server:.*|image: '${{ secrets.DOCKER_USERNAME }}/nodejs_server:${NODEJS_SERVER_TAG}}'|" docker-compose.yml
          docker-compose pull
          docker-compose up -d

