name: CI/CD Pipeline

on:
  push:
    tags:
      - 'v*.*.*'

env:
  HELM_VERSION: v3.15.3
  CHART_NAME: "nodejs-k8s"
  KUBE_NAMESPACE: "nodejs-k8s-development"
  DOCKER_IMAGE: "levon72/nodejs_server"

jobs:
  build:
    runs-on: ubuntu-20-04-dind
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check system info
        run: |
          echo "=== System Info ==="
          uname -a
          echo "=== OS Release ==="
          cat /etc/os-release

      - name: Check Docker version
        run: |
          echo "=== Docker Version ==="
          docker --version
          echo "=== Docker Info ==="
          docker info

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ github.ref_name }}

  deploy:
    runs-on: ubuntu-20-04-dind
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Deploy with Helm
        run: |
          helm upgrade --install ${{ env.CHART_NAME }} .helm \
            --namespace ${{ env.KUBE_NAMESPACE }} \
            --set image=${{ env.DOCKER_IMAGE }} \
            --set imageTag=${{ github.ref_name }} \
            --set imagePullSecrets[0].name=nodejs-k8s-gitlab-registry \
            --debug \
            --atomic \
            --timeout 240s

