name: CI/CD Pipeline

on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nodejs_server:${{ github.ref_name }}

      - name: Update Docker tag in docker-compose.yml
        run: |
          cd /home/stas/Simple-NodeJS-Server
          TAG=${{ github.ref_name }}
          sed -i "s|\${TAG:-latest}|$TAG|g" docker-compose.yml

      - name: Pull and redeploy Docker containers
        run: |
          cd /home/stas/Simple-NodeJS-Server
          docker-compose pull app
          docker-compose up -d

