name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nodejs-server:${{ github.sha }} .

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-server:${{ github.sha }}

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/nodejs-server:${{ github.sha }}

      - name: Restart Docker containers
        run: |
          cd /path/to/your/docker-compose-directory
          sed -i "s|image: .*$|image: ${{ secrets.DOCKER_USERNAME }}/nodejs-server:${{ github.sha }}|g" docker-compose.yml
          docker-compose down
          docker-compose up -d

